const PDFDocument = require('pdfkit');

const generateDirectivePDF = (directive, user) =>
  new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end',  () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header band
    doc.rect(0, 0, doc.page.width, 100).fill('#0f172a');
    doc.fillColor('#ffffff').fontSize(26).font('Helvetica-Bold').text('WillTrail', 50, 30);
    doc.fontSize(11).font('Helvetica').text('Advance Directive & Emergency Medical Record', 50, 62);
    doc.fillColor('#0f172a').moveDown(2);

    const metaY = 120;
    doc.fontSize(10).fillColor('#64748b')
       .text(`Generated: ${new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}`, 50, metaY)
       .text(`Document ID: ${directive._id}`, 50, metaY + 16);
    doc.moveTo(50, metaY + 40).lineTo(545, metaY + 40).strokeColor('#e2e8f0').stroke();

    const sectionTitle = (title, y) => {
      doc.rect(50, y, 495, 24).fill('#f1f5f9');
      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text(title, 58, y + 6);
      doc.font('Helvetica');
    };

    const field = (label, value, x, y, width = 220) => {
      if (!value) return;
      doc.fillColor('#64748b').fontSize(9).text(label.toUpperCase(), x, y);
      doc.fillColor('#0f172a').fontSize(10).text(String(value), x, y + 12, { width });
    };

    let y = 180;

    sectionTitle('PERSONAL INFORMATION', y); y += 34;
    field('Full Name', directive.personalInfo?.fullName, 50, y);
    field('Date of Birth', directive.personalInfo?.dateOfBirth ? new Date(directive.personalInfo.dateOfBirth).toLocaleDateString() : '', 290, y);
    y += 44;
    field('Blood Type', directive.personalInfo?.bloodType, 50, y);
    field('Primary Language', directive.personalInfo?.primaryLanguage, 290, y);
    y += 44;

    sectionTitle('EMERGENCY CONTACTS', y); y += 34;
    (directive.emergencyContacts || []).forEach((c, i) => {
      field(`Contact ${i+1} — ${c.relationship}`, `${c.name}   |   ${c.phone}`, 50, y, 490);
      y += 36;
    });

    sectionTitle('MEDICAL CONDITIONS', y); y += 34;
    field('Diagnosed Conditions', directive.medicalInfo?.conditions?.join(', ') || 'None', 50, y, 490); y += 36;
    field('Current Medications',  directive.medicalInfo?.medications?.join(', ') || 'None', 50, y, 490); y += 36;
    field('Known Allergies',      directive.medicalInfo?.allergies?.join(', ')   || 'None', 50, y, 490); y += 44;

    sectionTitle('CARE PREFERENCES', y); y += 34;
    field('CPR Preference', directive.carePreferences?.cprPreference, 50, y);
    field('Mechanical Ventilation', directive.carePreferences?.mechanicalVentilation, 290, y); y += 36;
    field('Organ Donation', directive.carePreferences?.organDonation ? 'Yes — Organ Donor' : 'Not specified', 50, y); y += 44;

    if (directive.healthcareAgent?.name) {
      sectionTitle('DESIGNATED HEALTHCARE AGENT', y); y += 34;
      field('Agent Name', directive.healthcareAgent.name, 50, y);
      field('Relationship', directive.healthcareAgent.relationship, 290, y); y += 36;
      field('Phone', directive.healthcareAgent.phone, 50, y);
      field('Email', directive.healthcareAgent.email, 290, y); y += 44;
    }

    doc.moveTo(50, doc.page.height - 60).lineTo(545, doc.page.height - 60).strokeColor('#e2e8f0').stroke();
    doc.fillColor('#94a3b8').fontSize(8)
       .text('Generated by WillTrail · Review with your healthcare provider · Store in a visible location',
             50, doc.page.height - 48, { width: 490, align: 'center' });
    doc.end();
  });

module.exports = { generateDirectivePDF };
